import {readFile,writeFile} from 'node:fs/promises';
const weightsUrl='https://www.taifex.com.tw/cht/9/futuresQADetail';
const reportUrl=d=>'https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&date='+d.replaceAll('-','')+'&type=ALLBUT0999';
const clean=s=>String(s??'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim();
const numeric=v=>{const s=clean(v).replaceAll(',','');if(!/^[+-]?\d+(?:\.\d+)?$/.test(s))throw new Error('資料包含缺漏或無效數值');const n=Number(s);if(!Number.isFinite(n))throw new Error('數值無效');return n};
const price=v=>{const n=numeric(v);if(n<=0)throw new Error('收盤價缺漏或無效');return n};
async function get(url,type='json'){const r=await fetch(url,{headers:{Accept:'application/json,text/html','User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('官方資料來源連線失敗 '+r.status);return type==='text'?r.text():r.json()}
function parseWeights(html){const rows=[];for(const tr of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const c=[...tr[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>clean(x[1]));for(let i=0;i+3<c.length;i+=4){const rank=Number(c[i]);if(rank>=1&&rank<=12&&/^\d{4,6}$/.test(c[i+1]))rows.push({rank,code:c[i+1],name:c[i+2],weight:numeric(c[i+3].replace('%',''))/100})}}rows.sort((a,b)=>b.weight-a.weight);if(rows.length!==12||new Set(rows.map(x=>x.code)).size!==12||rows.some(x=>x.weight<=0||x.weight>=1))throw new Error('十二檔權重不完整');const m=clean(html).replace(/\s+/g,' ').match(/資料日期[：:]\s*(\d{3,4})\/(\d{1,2})\/(\d{1,2})/);if(!m)throw new Error('權重日期缺漏');const y=Number(m[1])+(m[1].length===3?1911:0);return{rows,date:y+'-'+m[2].padStart(2,'0')+'-'+m[3].padStart(2,'0')}}
function parseReport(raw,date){if(raw.stat!=='OK'||raw.date!==date.replaceAll('-','')||!Array.isArray(raw.tables))throw new Error(date+' 完整收盤報表尚未發布或為休市日');const table=raw.tables.find(t=>t.fields?.includes('證券代號')&&t.fields?.includes('收盤價'));const it=raw.tables.find(t=>t.fields?.includes('收盤指數')&&t.data?.some(r=>r[0]==='發行量加權股價指數'));if(!table||!it)throw new Error(date+' 收盤資料不完整');const ir=it.data.find(r=>r[0]==='發行量加權股價指數'),indexClose=price(ir[it.fields.indexOf('收盤指數')]),sg=clean(ir[it.fields.indexOf('漲跌(+/-)')]),mag=numeric(ir[it.fields.indexOf('漲跌點數')]);if(mag!==0&&!['+','-'].includes(sg))throw new Error('指數漲跌符號缺漏');const stocks=new Map,ci=table.fields.indexOf('證券代號'),ni=table.fields.indexOf('證券名稱'),pi=table.fields.indexOf('收盤價');for(const r of table.data)stocks.set(clean(r[ci]),{name:clean(r[ni]),close:r[pi]});return{date,indexClose,indexChange:mag*(sg==='-'?-1:1),stocks}}
const roc=s=>{const m=s.match(/^(\d{3})\/(\d{2})\/(\d{2})$/);if(!m)throw new Error('交易日期格式錯誤');return(Number(m[1])+1911)+'-'+m[2]+'-'+m[3]};
async function dates(target){const load=async d=>{const j=await get('https://www.twse.com.tw/exchangeReport/FMTQIK?response=json&date='+d.replaceAll('-',''));if(j.stat!=='OK')throw new Error('交易日資料缺漏');return j.data.map(r=>roc(r[0]))};let all=await load(target);if(all.filter(d=>d<target).length<2){const d=new Date(target+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-1);all.push(...await load(d.toISOString().slice(0,10)))}return[...new Set(all)].filter(d=>d<=target).sort()}
function calculate(date,previousDate,current,previous,weights){if(previousDate>=date||weights.date>date)throw new Error('日期不一致');const change=current.indexClose-previous.indexClose;if(Math.abs(change-current.indexChange)>.021)throw new Error('前一交易日指數不吻合');const stocks=weights.rows.map(w=>{const c=current.stocks.get(w.code),p=previous.stocks.get(w.code);if(!c||!p)throw new Error(w.code+' 缺少收盤資料');const close=price(c.close),previousClose=price(p.close),change=close-previousClose,changePct=change/previousClose*100;return{...w,name:c.name,close,previousClose,change,changePct,points:previous.indexClose*w.weight*changePct/100}});const positive=stocks.reduce((s,r)=>s+Math.max(r.points,0),0),negative=stocks.reduce((s,r)=>s+Math.min(r.points,0),0);return{date,previousDate,weightDate:weights.date,savedAt:new Date().toISOString(),index:{close:current.indexClose,previousClose:previous.indexClose,change,changePct:change/previous.indexClose*100},stocks,totals:{positive,negative,net:positive+negative},methodology:'previous-index-close × published-weight × close-to-close-return/v1',sources:{current:reportUrl(date),previous:reportUrl(previousDate),weights:weightsUrl}}}
const clock=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const v=t=>clock.find(x=>x.type===t).value,target=v('year')+'-'+v('month')+'-'+v('day'),minutes=Number(v('hour'))*60+Number(v('minute')),weekday=new Date(target+'T12:00:00Z').getUTCDay();if(weekday===0||weekday===6){console.log('Weekend: no record');process.exit(0)}if(minutes<810&&!process.env.FORCE_DATE){console.log('Before 13:30 Asia/Taipei: no record');process.exit(0)}const chosen=process.env.FORCE_DATE||target,allDates=await dates(chosen),previousDate=allDates.filter(d=>d<chosen).at(-1);if(!previousDate)throw new Error('缺少前一交易日');const path=new URL('../data/history.json',import.meta.url),history=JSON.parse(await readFile(path,'utf8'));if(history.some(r=>r.date===chosen)){console.log(chosen+' already stored');process.exit(0)}const [current,previous,weights]=await Promise.all([get(reportUrl(chosen)).then(x=>parseReport(x,chosen)),get(reportUrl(previousDate)).then(x=>parseReport(x,previousDate)),get(weightsUrl,'text').then(parseWeights)]);history.push(calculate(chosen,previousDate,current,previous,weights));history.sort((a,b)=>b.date.localeCompare(a.date));await writeFile(path,JSON.stringify(history,null,2)+'\n');console.log(chosen+' stored with 12 stocks');
